// AUTH TYPES
export const HYDRATE_USER = "HYDRATE_USER";

//Logout USER
export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

//CHATROOMS
export const GET_CHATROOMS = "GET_CHATROOMS";
export const GET_CHATROOMS_LOADING = "GET_CHATROOMS_LOADING";
export const GET_CHATROOMS_ERRORS = "GET_CHATROOMS_ERRORS";

//SETMESSAGES
export const SET_MESSAGES = "SET_MESSAGES";
